name: Docker Build

on:
  push:

jobs:
  getversion:
    runs-on: ubuntu-latest
    name: Obtain Marlin Version
    outputs:
      build-version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Set Marlin Build Version
        id: set-version
        run: |
          MARLIN_VERSION=$(wget \
            -qO - https://api.github.com/repos/MarlinFirmware/Marlin/releases/latest \
            | awk '/tag_name/{print $4;exit}' FS='[""]')
          echo Building Marlin ${MARLIN_VERSION}
          echo "::set-output name=version::${MARLIN_VERSION}"
  build:
    name: Build Marlin
    runs-on: ubuntu-latest
    needs: getversion
    env:
      MARLIN_VERSION: ${{ needs.getversion.outputs.build-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
            env.BUILDKIT_STEP_LOG_MAX_SIZE=10000000
            env.BUILDKIT_STEP_LOG_MAX_SPEED=100000000
          install: true

      - name: Cache
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: |
            /tmp/.buildx-cache
            pio_build
          key: ${{ matrix.arch }}-${{ env.MARLIN_VERSION }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.arch }}-${{ env.MARLIN_VERSION }}-

      - name: Build Builder
        run: |
          set -x
          docker build \
            --build-arg MARLIN_VERSION=${MARLIN_VERSION} \
            --tag ci:${{ github.run_number }} \
            --progress plain \
            --file ./Marlin/Dockerfile \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new \
            --load \
            ./Marlin
        
      - name: Build Marlin
        run: |
          set -x
          docker run \
            -v ${PWD}/pio_build:/marlin/.pio \
            ci:${{ github.run_number }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware-Marlin_v${{ env.MARLIN_VERSION }}-${{ github.run_number }}
          path: pio_build/build/mega2560/firmware.hex
          if-no-files-found: error
